### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Ironman778** [xiecat/fofax#11]
查询10000条数据的时候，碰到一种协议无法解析应该是。
参数：-fto -fs 10000

报错信息：
url.Parse parse "mc_nmf://124.xxxxxx:10001": first path segment in URL cannot contain colon

**Comment by Becivells** [comment]
你好，能提供查询语句么

**Comment by Ironman778** [comment]
/fofax -q 'org="Technology Co.,Ltd"'  -fto -fs 10000

大致是这样的，有点敏感发不了。

**Comment by Becivells** [comment]
好的收到了。咱们这边可以暂时可以不用加 `-fto` 直接输出。fto 会把协议加入进去类似 xxx://ip:port

**Comment by Becivells** [comment]
fto 适用于http/https。 mc_nmf 协议没有标题这一选项。无法使用。后期会加入提醒来解决这一问题
