### ISSUE TITLE
加入环境变量后无法加载配置文件

### ISSUE THREAD

**Issue by killpi** [xiecat/fofax#12]
windows10下将exe加入环境变量运行好像无法加载配置文件
![图片](https://user-images.githubusercontent.com/40231581/148357243-122a41fd-b8cb-42a8-bd15-8dd1c46a4142.png)
在exe文件目录下运行正常
![图片](https://user-images.githubusercontent.com/40231581/148357717-353131d3-c250-4a70-8407-ec7c267bef05.png)

**Comment by killpi** [comment]
找到原因了不好意思

**Comment by 0xf4n9x** [comment]
在Windows系统上，fofax优先读取同级目录下的配置文件，如果没有则会读取用户家目录下的`.config/fofax/`目录中的配置文件：
![image](https://user-images.githubusercontent.com/40891670/148508049-736c14c0-93da-4253-869b-080e42a0e948.png)
第二件事情是关于Windows CMD的转义问题：
```cmd
fofax.exe -q app=\"APACHE-Solr\" -debug
```
![image](https://user-images.githubusercontent.com/40891670/148508321-0a060319-32e7-46cb-8a1b-3e7147d8668c.png)
