### ISSUE TITLE
windows报错：

### ISSUE THREAD

**Issue by lishang520** [xiecat/fofax#16]
1、执行命令：fofax -q 'app="APACHE-Solr"'
2、报错如下
2022/03/05 21:25:53 [INFO] The currently used fofax is the latest version
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/xiecat/fofax/internal/cli.updateFoFaXVersionToLatest()
        /home/runner/work/fofax/fofax/internal/cli/update.go:60 +0x45f
github.com/xiecat/fofax/internal/cli.updateTips({0x11a2100, 0x14})
        /home/runner/work/fofax/fofax/internal/cli/update.go:24 +0xc5
github.com/xiecat/fofax/internal/cli.checkUpdateInfo()
        /home/runner/work/fofax/fofax/internal/cli/parser.go:415 +0x1f9
github.com/xiecat/fofax/internal/cli.ParseOptions()
        /home/runner/work/fofax/fofax/internal/cli/parser.go:318 +0x33e
main.main()
        /home/runner/work/fofax/fofax/cmd/fofax/fofax.go:11 +0x19

这是啥问题啊？fofa的邮箱和key都添加了的

**Comment by lishang520** [comment]
@Becivells @TardC

**Comment by Becivells** [comment]
你好看起来像是更新出了bug 
请在配置文件里加入
```
disable-update: true
```
临时缓解。我们马上修复此问题

**Comment by Becivells** [comment]
更新后即可解决

**Comment by lishang520** [comment]
> 更新后即可解决

你们这bug处理速度，真的快，，我还打算等几天才能解决呢

**Comment by Becivells** [comment]
如果有疑问可以微信联系，github可能会有延迟
