### ISSUE TITLE
命令行fx规则和fofa语法结合查询闭合问题导致命令不存在

### ISSUE THREAD

**Issue by lishang520** [xiecat/fofax#17]
windows查询转义问题，请参考文档：https://fofax.xiecat.fun/faq/#%E9%80%9A%E8%BF%87%E5%8F%82%E6%95%B0%E6%8C%87%E5%AE%9A%E6%9F%A5%E8%AF%A2

**Comment by Becivells** [comment]
如无疑问这个 issus 关闭了？

**Comment by 0xf4n9x** [comment]
移至 #18 讨论，此issue将被关闭。
