### ISSUE TITLE
按时间段查询会报语法错误

### ISSUE THREAD

**Issue by ifofor** [xiecat/fofax#24]
比如说：
echo 'after="2017-01-01" && before="2017-10-01"' | fofax.exe --debug
结果：
2022/07/18 11:45:38 [DEBUG] FoFa Size : 100
2022/07/18 11:45:38 [DEBUG] FoFa input Query of: after="2017-01-01" && before="2017-10-01"
2022/07/18 11:45:38 [DEBUG] https://fofa.info/api/v1/search/all?email=*****@*************&key=********************************&qbase64=YWZ0ZXI9IjIwMTctMDEtMDEiICYmIGJlZm9yZT0iMjAxNy0xMC0wMSI=&size=100&page=1&fields=host,port,ip,lastupdatetime
2022/07/18 11:45:38 [DEBUG] Resp Time: 343.00/millis
2022/07/18 11:45:38 [ERRO] FoFa Response ErrMsg: [820000] FOFA Query Syntax Incorrect

**Comment by 0xf4n9x** [comment]
网页版FOFA查询这条语句正常，但是FOFA API不允许查询语句中同时拥有`after`和`before`两个关键词。

**Comment by ifofor** [comment]
> 网页版FOFA查询这条语句正常，但是FOFA API不允许查询语句中同时拥有`after`和`before`两个关键词。

哦哦好的，感谢！fofax很不错！
