### ISSUE TITLE
fofa会员制更新了，普通永久会员权限查询出错

### ISSUE THREAD

**Issue by Maysec** [xiecat/fofax#27]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/53160265/229549896-0a847263-3557-4d23-82f2-3ff762e7b9ef.png">

**Comment by Becivells** [comment]
我看看

**Comment by Becivells** [comment]
加我微信可以么？YmVjaXZlbGxzCg== 我现在对这个会员机制不太清楚

**Comment by Becivells** [comment]
已经更新

**Comment by Maysec** [comment]
> 已经更新

经测试已修复 师傅幸苦
