### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by LOONG001** [xiecat/fofax#30]
![image](https://user-images.githubusercontent.com/34571314/233891559-9637632a-fe3e-4c62-a1f8-4eca4db9969d.png)
不知道什么原因

**Comment by Becivells** [comment]
网络问题导致的。再次运行就行了。这个问题已经修复了。等下个版本网络出错就没这个问题了

**Comment by Becivells** [comment]
新打了一个更新 https://github.com/xiecat/fofax/releases/tag/v0.1.44
你更新一下吧

**Comment by LOONG001** [comment]
> 新打了一个更新 https://github.com/xiecat/fofax/releases/tag/v0.1.44 你更新一下吧

ok了，感谢师傅
