### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by xiaozhaha** [xiecat/fofax#31]
搜索语句带有中文的时候，似乎不能正确的搜索。
.\fofax.exe -q 'app="张三-camera"' -ffi -fs 5 -fe -debug

实际搜索结果如下：
2023/06/03 14:39:04 [DEBUG] FoFa Size : 5
2023/06/03 14:39:04 [DEBUG] FoFa input Query of: app=
2023/06/03 14:39:04 [DEBUG] https://fofa.info/api/v1/search/all?email=*****@*************&key=9161************************b720&qbase64=YXBwPQ==&size=5&page=1&fields=protocol,ip,port,host,type
2023/06/03 14:39:06 [DEBUG] Resp Time: 1398.00/millis
2023/06/03 14:39:06 [DEBUG] Fofa Api Query: "app"
2023/06/03 14:39:06 [SUCC] Fetch Data From FoFa: [5/363027531]
![image](https://github.com/xiecat/fofax/assets/48639007/dee92385-92b2-4204-b135-a5b65811a83c)

**Comment by 0xf4n9x** [comment]
与[上次其他人反馈的](https://github.com/xiecat/fofax/issues/18#issuecomment-1555729961)一样，目前在Windows上使用fofax，如果查询语句中存在中文，先暂时不要用powershell，换用其他终端工具，或者按照如下所说，从文件中读取查询语句。

<img width="830" alt="image" src="https://github.com/xiecat/fofax/assets/40891670/ed19ccd5-ca3b-457b-b73c-e62f9f3d8a0e">

**Comment by xiaozhaha** [comment]
okok，谢谢师傅了。😃
