### ISSUE TITLE
使用qf 查询时候，遇到ipv6导致查询失败

### ISSUE THREAD

**Issue by init47** [xiecat/fofax#32]
[ERRO] url.Parse parse "https://2407:c080:17ef:ffff::7703:d86e": invalid port ":d86e" after host

**Comment by init47** [comment]
![image](https://github.com/xiecat/fofax/assets/8731224/a599d98e-685a-4e0e-a486-f11eb560ad99)
失败后，导出文件为空。

**Comment by Becivells** [comment]
临时修复一下。你可以试试

**Comment by Becivells** [comment]
https://github.com/xiecat/fofax/releases/tag/v0.1.45
