### ISSUE TITLE
配置文件不生效,mac m2

### ISSUE THREAD

**Issue by secpool2000** [xiecat/fofax#36]
![image](https://github.com/xiecat/fofax/assets/53165336/87d79e28-65d2-4de6-b2f0-8073fb6ad0ad)
![image](https://github.com/xiecat/fofax/assets/53165336/baa7b484-305e-4ac6-ad49-71dd44e2f953)

**Comment by rhymsc** [comment]
**there is a space between ":" and the email or key**
fofa-email: xxxxxxx@gmail.com 
fofakey: 1906xxxxxxxxxx

**not like below**
fofa-email:xxxxxxx@gmail.com 
fofakey:1906xxxxxxxxxx
