### ISSUE TITLE
fx规则-ss命令使用建议

### ISSUE THREAD

**Issue by zhangmuran** [xiecat/fofax#5]
fx规则使用-ss查看详情时会列出与所有规则的匹配过程，看起来不是很友好。还有就是不支持模糊查询，记不住名称或编号得挨个翻。

**Comment by Becivells** [comment]
十分感谢你的建议。显示编号这个是debug信息没有删除。中午已经注意到这个问题了。刚刚release一个版本已经去掉了。因为-ss是属于显示单个信息的。如果模糊匹配可能会匹配多个。你这里有更好的方法么，咱们可以讨论一下

**Comment by zhangmuran** [comment]
是否可以-l参数后加一个模糊匹配字段，这样只有-l显示全部列表，-l+匹配关键词显示模糊匹配列表，-ss依旧显示单条的详细信息。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月27日(周一) 中午1:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiecat/fofax] fx规则-ss命令使用建议 (Issue #5)




 
十分感谢你的建议。显示编号这个是debug信息没有删除。中午已经注意到这个问题了。刚刚release一个版本已经去掉了。因为-ss是属于显示单个信息的。如果模糊匹配可能会匹配多个。你这里有更好的方法么，咱们可以讨论一下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Becivells** [comment]
多个搜索可以使用 -s 支持模糊查询如
```shell
fofax -s 'fofa'
fofax -s 'tag=fofa'
fofax -s 'rulename=vmware;tag=log4j2'
fofax -s 'rulename=St;tag=log4j2;author=jsqj'
```

**Comment by zhangmuran** [comment]
好的，感谢您的回复。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月27日(周一) 中午1:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiecat/fofax] fx规则-ss命令使用建议 (Issue #5)




 
多个搜索可以使用 -s 支持模糊查询如
 fofax -s 'fofa' fofax -s 'tag=fofa' fofax -s 'rulename=vmware;tag=log4j2' fofax -s 'rulename=St;tag=log4j2;author=jsqj'
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Becivells** [comment]
好的我们这边把文档完善一下。如果您这边没问题。我就把 issus 关掉了
