### ISSUE TITLE
mac下无法使用 timeout

### ISSUE THREAD

**Issue by fengwenhua** [xiecat/fofax#9]
尝试了 v0.1.17 和 v0.1.15，都是提示 timeout，排除了网络的问题

于是把源码下载了下来编译，发现`CGO_ENABLED=1`下编译，是不会有问题的，不知道是不是这个导致的？

![image](https://user-images.githubusercontent.com/26518808/147728737-71b468a1-922c-4aed-a7f5-047001da78b1.png)

**Comment by Becivells** [comment]
V1ll4n 给出一个解决方案:
```
os.Setenv("GODEBUG","netdns=go")
```
https://go.dev/src/net/net.go?s=16228:16259
force cgo resolver + ENABLE_CGO 会让 dns 挂掉，取决于系统环境

**Comment by Becivells** [comment]
做了个小实验。证明是 dns 解析的问题，V1ll4n 师傅给的方案还是不行。实验内容如下
本地开一个web服务 使用 fofax -fofa-url http://127.0.0.1:8080 -q "adf" 访问正常
本地开一个web服务 使用 fofax -fofa-url http://127.0.0.1.xip.io:8080 -q "adf" 访问出现上述错误 (127.0.0.1.xip.io ->127.0.0.1)

**Comment by Becivells** [comment]
目前准备移除 xhttp
